# Generated by Django 3.0.1 on 2019-12-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='currently_invested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='investment_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='pitchers',
            field=models.ManyToManyField(to='edge.Member'),
        ),
    ]
