# Generated by Django 3.0.1 on 2019-12-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0002_auto_20191231_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='catalysts',
            field=models.TextField(default='No Catalysts'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='entry_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='key_signposts',
            field=models.TextField(default='No Key Signposts'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='major_concerns',
            field=models.TextField(default='No Major Concerns'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='misperceptions',
            field=models.TextField(default='No Misperceptions'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='other_notes',
            field=models.TextField(default='No Other Notes'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='pitch_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='reasons_for_weight',
            field=models.TextField(default='No Reasons for Weight'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='theses_for_investment',
            field=models.TextField(default='No Theses'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='threats_downside',
            field=models.TextField(default='No Threats'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='vote_count_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='vote_count_for',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='grad_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pitch_date',
            field=models.DateField(verbose_name='date pitched'),
        ),
    ]
