# Generated by Django 3.0.1 on 2019-12-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0007_auto_20191231_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='investment_strategy',
            field=models.CharField(choices=[('RV', 'Relative Value'), ('SSG', 'Special Situations'), ('GM', 'Global Macro'), ('Risk', 'Risk')], default='RV', max_length=4),
        ),
    ]
