# Generated by Django 3.0.1 on 2019-12-31 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0008_pitch_investment_strategy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitch',
            old_name='threats_downside',
            new_name='threats_downsides',
        ),
    ]
