# Generated by Django 3.0.4 on 2020-03-27 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('grad_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('long_investment', models.BooleanField(default=False)),
                ('stock_exchange_abbreviation', models.CharField(default='NYSE', max_length=30, verbose_name='Stock Exchange Abbreviation')),
                ('stock_ticker', models.CharField(default='AAPL', max_length=30)),
                ('pitch_date', models.DateField(verbose_name='Date Pitched')),
                ('vote_count_for', models.PositiveIntegerField(default=0)),
                ('vote_count_against', models.PositiveIntegerField(default=0)),
                ('investment_strategy', models.CharField(choices=[('RV', 'Relative Value'), ('SSG', 'Special Situations'), ('GM', 'Global Macro'), ('Risk', 'Risk')], default='RV', max_length=4)),
                ('investment_entered', models.BooleanField(default=False)),
                ('pitch_price', models.FloatField(default=0.0)),
                ('target_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('currently_invested', models.BooleanField(default=False)),
                ('theses_for_investment', models.TextField(default='No Theses')),
                ('misperceptions', models.TextField(default='No Misperceptions')),
                ('major_concerns', models.TextField(default='No Major Concerns')),
                ('catalysts', models.TextField(default='No Catalysts')),
                ('key_signposts', models.TextField(default='No Key Signposts')),
                ('reasons_for_weight', models.TextField(default='No Reasons for Weight')),
                ('threats_downsides', models.TextField(default='No Threats')),
                ('other_notes', models.TextField(default='No Other Notes')),
                ('exit_notes', models.TextField(blank=True, default='No Exit Notes', null=True)),
                ('pitchers', models.ManyToManyField(to='edge.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(default=None, upload_to='')),
                ('pitch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edge.Pitch')),
            ],
        ),
    ]
