# Generated by Django 3.0.1 on 2020-01-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0002_auto_20200101_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
