# Generated by Django 3.0.6 on 2020-06-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0002_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='template_name',
            field=models.CharField(default='mvo.html', max_length=200),
            preserve_default=False,
        ),
    ]
