# Generated by Django 3.0.1 on 2020-01-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0003_auto_20200101_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='question_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
