# Generated by Django 3.0.7 on 2020-06-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0003_tool_template_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitch',
            options={'verbose_name_plural': 'Pitches'},
        ),
    ]
