# Generated by Django 3.0.1 on 2019-12-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_auto_20191231_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='entry_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
