# Generated by Django 3.0.1 on 2020-01-01 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_auto_20200101_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='question_text',
        ),
        migrations.AddField(
            model_name='document',
            name='pitch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.Pitch'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
