# Generated by Django 3.0.7 on 2020-06-10 04:54

import aifedge.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_auto_20200609_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(default=None, storage=aifedge.storage_backends.PrivateDataStorage, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(default=None, storage=aifedge.storage_backends.PublicFileStorage, upload_to=''),
        ),
    ]
