# Generated by Django 3.0.1 on 2020-01-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0005_auto_20200101_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pitch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edge.Pitch'),
        ),
    ]
