# Generated by Django 3.0.7 on 2020-06-10 07:00

import aifedge.storage_backends
from django.db import migrations, models
import edge.models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0005_auto_20200610_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(storage=aifedge.storage_backends.PrivateDataStorage(), upload_to=edge.models.rename_data_file)),
            ],
        ),
    ]
