# Generated by Django 3.0.2 on 2020-03-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0006_auto_20200101_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='exit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
