# Generated by Django 3.0.1 on 2019-12-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0006_auto_20191231_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='stock_exchange_abbreviation',
            field=models.CharField(default='NYSE', max_length=30),
        ),
        migrations.AddField(
            model_name='pitch',
            name='stock_ticker',
            field=models.CharField(default='AAPL', max_length=30),
        ),
    ]
