# Generated by Django 3.0.7 on 2020-06-10 06:44

import aifedge.storage_backends
from django.db import migrations, models
import edge.models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0007_auto_20200610_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='upload',
            field=models.FileField(storage=aifedge.storage_backends.PrivateDataStorage(), upload_to=edge.models.rename_data_file),
        ),
    ]
